# Deploy to App Engine

name: Deploy to App Engine (development)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

env:
  APP_DIRECTORY: app

jobs:
  Upload:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: 'Checkout to current commit'
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.AUTH_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.AUTH_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.AUTH_PROJECT_ID }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Build app'
        run: 'cd $APP_DIRECTORY && npm install && npm run build && cd ..'
      
      - name: 'Deploy App Engine'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          working_directory: ${{ env.APP_DIRECTORY }}
          promote: false
